import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Basa Bari | FIND YOUR HOME - Across the Cities.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div><h1>Hwllo</h1></div>
    </div>
  )
}
